# Generated by Django 2.2.7 on 2019-11-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classification', '0002_auto_20191123_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
